monthly_income = int(input('Enter your monthly income: '))
monthly_expenses = int(input('Enter your monthly expenses: '))
monthly_savings = int(monthly_income - monthly_expenses)
projected_savings = int(monthly_savings * 12 + (monthly_savings * 12 * 0.05))
monthly_savings = str(monthly_savings)
projected_savings = str(projected_savings)
print(f'Your monthly savings are ${monthly_savings}.')
print(f'Projected savings after one year, with interest, is: ${projected_savings}.')
